default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5
  host: db
  port: 5432
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

production:
  <<: *default
  database: proposals_production

development:
  <<: *default
  database: proposals_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

test:
  <<: *default
  database: proposals_test
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  